# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from service_spec_bipartite import network_analytics_bipartite_pb2 as service__spec__bipartite_dot_network__analytics__bipartite__pb2


class NetowrkAnalyticsBipartiteStub(object):
  """/// End Bipartite graph

  /// Network Analytics Bipartite Services

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BipartiteGraph = channel.unary_unary(
        '/NetowrkAnalyticsBipartite/BipartiteGraph',
        request_serializer=service__spec__bipartite_dot_network__analytics__bipartite__pb2.BipartiteGraphRequest.SerializeToString,
        response_deserializer=service__spec__bipartite_dot_network__analytics__bipartite__pb2.BipartiteGraphResponse.FromString,
        )
    self.ProjectedGraph = channel.unary_unary(
        '/NetowrkAnalyticsBipartite/ProjectedGraph',
        request_serializer=service__spec__bipartite_dot_network__analytics__bipartite__pb2.ProjecetedGraphRequest.SerializeToString,
        response_deserializer=service__spec__bipartite_dot_network__analytics__bipartite__pb2.ProjecetedGraphResponse.FromString,
        )


class NetowrkAnalyticsBipartiteServicer(object):
  """/// End Bipartite graph

  /// Network Analytics Bipartite Services

  """

  def BipartiteGraph(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProjectedGraph(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NetowrkAnalyticsBipartiteServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BipartiteGraph': grpc.unary_unary_rpc_method_handler(
          servicer.BipartiteGraph,
          request_deserializer=service__spec__bipartite_dot_network__analytics__bipartite__pb2.BipartiteGraphRequest.FromString,
          response_serializer=service__spec__bipartite_dot_network__analytics__bipartite__pb2.BipartiteGraphResponse.SerializeToString,
      ),
      'ProjectedGraph': grpc.unary_unary_rpc_method_handler(
          servicer.ProjectedGraph,
          request_deserializer=service__spec__bipartite_dot_network__analytics__bipartite__pb2.ProjecetedGraphRequest.FromString,
          response_serializer=service__spec__bipartite_dot_network__analytics__bipartite__pb2.ProjecetedGraphResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'NetowrkAnalyticsBipartite', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
